### ISSUE TITLE
Puppet fails when using tar.gz

### ISSUE THREAD

**Issue by ngeorgieff** [antoineco/aco-oracle_java#1]
[root@is-lab-p01 tests]# cat init.pp
class { 'oracle_java':
  version => '7u80',
  type    => 'jdk',
  format  => 'tar.gz',
  check_checksum  => false,
}

[root@is-lab-p01 tests]# puppet apply init.pp
Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
Notice: Compiled catalog for is-lab-p01.it.ucla.edu in environment lab in 0.82 seconds

Error: Cannot alias Archive[extract java archive] to ["/usr/java/jdk-7u80-linux-x64.tar.gz"] at /etc/puppet/modules/oracle_java/manifests/install/targz.pp:22; resource ["Archive", "/usr/java/jdk-7u80-linux-x64.tar.gz"] already declared at /etc/puppet/modules/oracle_java/manifests/download.pp:41

**Comment by antoineco** [comment]
Hm, looks like some upstream changes broke my module :) Thanks for
reporting, I'm on it.

ngeorgieff <notifications@github.com> schrieb am Do., 18. Juni 2015 19:12:

**Comment by antoineco** [comment]
Hm, looks like some upstream changes broke my module :) Version 0.3.0 of [nanliu-archive](https://forge.puppetlabs.com/nanliu/archive/changelog) more specifically.

Thanks for reporting, I'm on it.

**Comment by antoineco** [comment]
Fix released in 2.2.5!

**Comment by ngeorgieff** [comment]
Thank you for the lightning fix!

**Comment by antoineco** [comment]
Too fast apparently, I broke something with a typo. Use v2.2.6 instead
