### ISSUE TITLE
Add support to JRE/JDK 6 version

### ISSUE THREAD

**Issue by jguilhermemv** [antoineco/aco-oracle_java#16]
The module doesn't support any version older than 7th. However, many enviroments, specially production ones for legacy systems still use Java 6 (u22 specifically) or even 5, for example.

Additionally, the module doesn't execute any source command when setting enviroment variables with Augeas, so when a project is provisioned the enviroment variable is not accessible and require a new ssh session to load. That's bad, because other modules may rely on this one, for example, a JBoss module.

Could you please solve this issue?

**Comment by antoineco** [comment]
Java 6 support was [removed from v2.0.0](https://github.com/antoineco/aco-oracle_java/commit/ae945edb616ca2ea76e7b1b3aad0a406fa0f18c4) because the format of the file name was different, and the way it was packaged extremely hacky. That said it shouldn't be too hard to restore it, I'm just not a big fan of supporting deprecated technology. I mean, who uses Puppet **and** Java 6? Just kidding ;)

Regarding the environment variables can you elaborate? Isn't Jboss supposed to be configured with the path to Java and so on? What if you installed several java versions and this module sets undesirable global environment variables?

**Comment by jguilhermemv** [comment]
You're right saying that "no one shoud be using a deprecated technology". Well, for new projects that might true. However, in my experience with systems in production, companies aren't keen on changing stable enviroments — even ones using deprecated Java or JBoss versions — because it's too risky to make this move. Unless you want your module to be used only for really recent projects, it's ok, it's your call. But I do think that it would be much more useful if you support the 6th version, since it's widely used in legacy systems in production as well as much more people would make use of  your amazing work. You could change your javalist.pp to accept the older versions, I can help you with that if you want.

Answering your question: you set JAVA_HOME with Augeas, however, JBoss need this variable in the PATH to work properly. For a developer the scenario of a single VM with many Java versions is an exception. In most cases, even in companies we can see a single VM with a single Java and JBoss version. Due to that, I believe that your project should put the JAVA_HOME in the PATH, or at least accept a flag as parameter (add_java_home_to_path = true). It would be much more flexible. If you don't want it to go to the path, you can change it easily.

What do you think?

**Comment by antoineco** [comment]
I totally agree with the fact that I should support java 6 (I won't support java 5 however). I wrongly assumed nobody would use it because I've never faced the situation, and since I wanted to clean up my module I removed it. But it's a good suggestion.

Regarding java in the PATH, it's indirectly supported using the `add_alternative` parameter, which will ensure a symlink to the Java binaries is always present in /usr/bin. I could of course add more variables and let the user decide to set them or not.

**Comment by jguilhermemv** [comment]
> Regarding java in the PATH, it's indirectly supported using the add_alternative parameter, which will ensure a symlink to the Java binaries is always present in /usr/bin.

How so?

**Comment by antoineco** [comment]
Debian and Red Hat both support the "alternatives" system which allows you to easily switch versions of executables installed on the system. My module uses it to set /usr/bin/java without overwriting another installed version. Give it a try (the flag defaults to false)

**Comment by jguilhermemv** [comment]
@antoineco all right. Would you let me to fork this project to put the JDK6 support back and then I make a pull request for your acceptance?

**Comment by antoineco** [comment]
Of course, all contributions are welcome

**Comment by robachmann** [comment]
@jguilhermemv I just came across an environment where I'd like to install JDK 6 (1.6.0_45) with puppet. Have you already made any progress in this matter?

**Comment by jguilhermemv** [comment]
@240ch Yes. I've forked the project [here](https://github.com/jguilhermemv/aco-oracle_java) and solved this issue. In a few days I expect to send a pull request to @antoineco.

**Comment by robachmann** [comment]
@jguilhermemv fantastic news, thank you very much. I'm looking forward to the merge.

**Comment by antoineco** [comment]
I'm working on restoring support for Java 6 in the PR referenced above :point_up:
Only Java 6u45 (the latest) is supported so far, but this is probably enough.

Please checkout the `java6` branch and give me feedback if possible. I ran the following tests manually on CentOS 7 and everything worked as expected:

```
$ puppet apply -t -e 'class { "oracle_java": version => "6", format => "tar.gz", add_alternative => true }'
[...]
$ java -version
java version "1.6.0_45"
```

```
$ puppet apply -t -e 'class { "oracle_java": version => "6", format => "rpm" }'
[...]
$ java -version
java version "1.6.0_45"
```

**Comment by robachmann** [comment]
@antoineco thanks, I'd love to test it. But as I'm not that familiar with puppet, would you mind explaining me briefly, how to do that? I define the details of the JDK installations in `/etc/puppet/manifests/site.pp` as follows:

```
class { 'oracle_java':
  version => '7u80',
  type    => 'jdk',
  add_alternative => true
} ->
oracle_java::installation { '8u51':
  type => 'jdk',
  add_alternative => true
} 
```

then I simply call `sudo puppet module install aco-oracle_java --version 2.4.1` and set JAVA_HOME afterwards manually. 

Your lines above throw this error:

```
user@ubuntu-user:~/aco-oracle_java$ git branch
* java6
  master
user@ubuntu-user:~/aco-oracle_java$ puppet apply -t -e 'class { "oracle_java": version => "6", format => "tar.gz", add_alternative => true }'
Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class oracle_java at line 1 on node ubuntu-user.localdomain
```

**Comment by antoineco** [comment]
@240ch it looks like the module is not in your modulepath, you can check with `puppet module list`. If you cloned the git repo you have to make sure you did it inside `$modulepath/oracle_java`, and that the dependencies required by my module are present on the system. Write me per email directly if you need support :)
