### ISSUE TITLE
Download behind http proxy

### ISSUE THREAD

**Issue by not-known** [antoineco/aco-oracle_java#2]
The download does not work from from behind an http proxy. Is it possible to make this configurable, or like other modules use the systems wget with its own independent proxy config?
Other less preferred option is to add a custom source so we can pre download the jdk files and make them available internally.
The module is worth using, so thank you!

**Comment by antoineco** [comment]
That's a relevant question. I'm using a dependency to fetch the archives and do the checksum validation, I'll file an issue upstream and see how this could be handled.

**Comment by antoineco** [comment]
Hey @not-known, the [module I depend on](https://github.com/nanliu/puppet-archive) does not allow users to create GitHub Issues, so I guess I'll have to put my hands in the Ruby code.

Under the hood it uses a gem called Faraday, which supports http proxies so this is definitely doable but I can't really tell you how long I need.

Are you still interested or did you find a workaround?

**Comment by not-known** [comment]
Hi @antoineco well yes sure. At the moment I provision my java based servers still by hand. The other existing modules for Oracle java do not fit my needs or have a codebase of doubtful quality. When you can fix it with a little Ruby code, that perfectly fine by me. I'm not in a hurry (3 weeks vacation starting next week) so take your time. Thanks for your support.

**Comment by antoineco** [comment]
Hi @not-known, I have good news for you, `nanliu-archive` now supports `wget` as a provider alongside `ruby` (puppet-community/puppet-archive#60) so everything should work out of the box :+1: 

I have to wait for the next version (puppet-community/puppet-archive#62) to be released on the Forge in order to be able to push a new version on my side, but if installing modules from GitHub is an option for you the following fix may solve your proxy issue.

**Comment by not-known** [comment]
Hi @antoineco, that's is good news. I'll wait a little while to see if it will be released to forge soon so it won't break the module versioning. If not i'll patch the module myself.
Thanks for the support!

**Comment by antoineco** [comment]
@not-known wget support is finally here https://forge.puppetlabs.com/puppet/archive/changelog :tada:

**Comment by antoineco** [comment]
Reverted in 80cbc71dda5001bc408571bcac564a468e19a5c4
