### ISSUE TITLE
Version 2.7.0 adds support for Java 8u101 but the version validation check fails

### ISSUE THREAD

**Issue by ghost** [antoineco/aco-oracle_java#20]
Hi,

I've just updated to the latest version of the module and tried to deploy Java version "8u101"

Puppet is erroring with:

`Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, $version must be formated as 'major'u'minor' or just 'major' at /etc/puppetlabs/code/environments/production/modules/oracle_java/manifests/init.pp:72:3`

Looking at the init.pp I believe the issue is here:
`validate_re($version, '^([0-9]|[0-9]u[0-9]{1,2})$', '$version must be formated as \'major\'u\'minor\' or just \'major\'')`

The Regex needs to be updated to accept version 101 as a valid version.

Thanks

**Comment by antoineco** [comment]
Uh oh, this fish got through the net apparently! For the first time in history a Java version has 3 digits, thanks for noticing the regexp was not matching that new case.

I'll push a hotfix in one hour or so.

**Comment by ghost** [comment]
No problem :) Thanks for producing such a great Puppet Module!

**Comment by antoineco** [comment]
Upgrading the module to the hotfix version with `puppet module upgrade aco/oracle_java --version=2.7.0-hf` fixes the issue.

```
:/ # puppet apply -e 'class { oracle_java : version => "8u101"} '
Notice: Applied catalog in 36.42 seconds

:/ # /usr/java/default/bin/java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```
