### ISSUE TITLE
Does not work on Fedora 24

### ISSUE THREAD

**Issue by looppair** [antoineco/aco-oracle_java#22]
I did simply `include oracle_java`, and got the following error message:

> Error: Could not autoload puppet/provider/archive/ruby: Unable to find archive module in modulepath /etc/puppet/modules:/opt/puppetlabs/puppet/modules
> Error: Could not autoload puppet/type/archive: Could not autoload puppet/provider/archive/ruby: Unable to find archive module in modulepath /etc/puppet/modules:/opt/puppetlabs/puppet/modules
> Error: Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/archive: Could not autoload puppet/provider/archive/ruby: Unable to find archive module in modulepath /etc/puppet/modules:/opt/puppetlabs/puppet/modules at […]/oracle_java/manifests/download.pp:35:5 on node […]

Module structure:

```
└─┬ aco-oracle_java (v2.7.1)
  ├── puppet-archive (v1.1.1)
  └── puppetlabs-stdlib (v4.12.0)
```

Using Puppet 4.2.1-3.fc24 from the `@commandline` repository (I just upgraded from Fedora 21 so I'm quite sure it was installed from the official repos). Modules are installed in the same directory as all my other modules (a Git repository directory in my home directory). I'm using agentless Puppet.

**Comment by antoineco** [comment]
I can not reproduce on a fresh Fedora 24, could you describe your environment in more details?
- What version of Puppet are you using?
- From which repo?
- Did you override the modulepath somewhere?

## 

Here is my test log. I used Docker to start a bare OS.

```
❯❯❯ docker run -it --rm fedora:24 bash -il
24: Pulling from library/fedora
...
```

```
[root@0ad0df141e49 /]# dnf install http://yum.puppetlabs.com/puppetlabs-release-pc1-fedora-24.noarch.rpm
...
Installed:
  puppetlabs-release-pc1.noarch 1.0.0-2.fedoraf24

Complete!
```

```
[root@0ad0df141e49 /]# dnf install puppet-agent findutils -y
...
Installed:
  puppet-agent.x86_64 1.6.1-1.fedoraf24                                                              tar.x86_64 2:1.28-7.fc24

Complete!
```

```
[root@0ad0df141e49 /]# puppet -V
4.6.1
```

```
[root@0ad0df141e49 /]# source /etc/profile.d/puppet-agent.sh
```

```
[root@0ad0df141e49 /]# puppet config print
...
modulepath = /etc/puppetlabs/code/environments/production/modules:/etc/puppetlabs/code/modules:/opt/puppetlabs/puppet/modules
...
```

```
[root@0ad0df141e49 /]# puppet module install aco-oracle_java
Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Notice: Installing -- do not interrupt ...
/etc/puppetlabs/code/environments/production/modules
└─┬ aco-oracle_java (v2.7.1)
  ├── puppet-archive (v1.1.1)
  └── puppetlabs-stdlib (v4.12.0)
```

```
[root@0ad0df141e49 /]# puppet apply -e 'include oracle_java' 
Notice: Compiled catalog for 0ad0df141e49.local in environment production in 0.61 seconds
Notice: /Stage[main]/Oracle_java::Download/File[/usr/java]/ensure: created
Notice: /Stage[main]/Oracle_java::Download/Archive[/usr/java/jre-8u102-linux-x64.rpm]/ensure: download archive from http://download.oracle.com/otn-pub/java/jdk/8u102-b14/jre-8u102-linux-x64.rpm to /usr/java/jre-8u102-linux-x64.rpm  without cleanup
Notice: /Stage[main]/Oracle_java::Install::Rpm/Package[jre]/ensure: created
Notice: /Stage[main]/Oracle_java::Install::Rpm/Package[jre]: Triggered 'refresh' from 1 events
Notice: Applied catalog in 15.63 seconds
```

```
[root@0ad0df141e49 /]# java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```

**Comment by looppair** [comment]
Please see my updated post for answers.

**Comment by antoineco** [comment]
My guess is that during the update Puppet's modulepath was changed to `/etc/puppet/modules:/opt/puppetlabs/puppet/modules`, but your modules are in none of these directories.

I would compare the output of `puppet config print modulepath` and the content of the `puppet.conf` file if I were you. You could also try to reinstall these 3 modules, that should naturally fix the issue.

**Comment by antoineco** [comment]
Sorry, I missed that detail about your modules lying inside your home directory. In that case what I said makes even more sense, if your home directory is not inside Puppet's `modulepath` or `basemodulepath` it can simply not work. Unfortunately that's nothing this module can change.

Please refer to: https://docs.puppet.com/puppet/latest/reference/configuration.html#basemodulepath and https://docs.puppet.com/puppet/latest/reference/environments.html for learning how to set up your environment so that it searches modules inside a custom location.
