### ISSUE TITLE
Alternatives does not provide the "latest" path

### ISSUE THREAD

**Issue by staylorx** [antoineco/aco-oracle_java#27]
For example,
1. Install JDK 8u101 which installs the jdk and sets /usr/java/default link to /usr/java/jdk1.8.0_101. It does not provide a '/usr/java/latest' path.
2. Set the latest path in a separate action.
3. Install JDK 8u111. Installs correctly to /usr/java/jdk1.8.111 and updates the default link. But the latest link still points to the old one.  This is expected since I created it manually, but unexpected from an 'alternatives' standpoint.

_[Aside, I should say I really like this module and thank you for creating it.]_

**Comment by antoineco** [comment]
Fair point, I've been wondering how I could implement that in a reliable manner actually :) The challenge is to make that link point to the actual latest version, and not the version which was installed last.

For example, I could install version 7, then version 8 in a separate installation, and yet another Java 7 in a third installation. Which class checks which version is the latest, which one creates the symlink?

I believe we could determine that with a fact, a simple Ruby script would do. But then again, facts are executed **before** requesting the catalog :(

Any thoughts?

_[Thanks for the nice comment, much appreciated!]_

**Comment by staylorx** [comment]
I've got an ansible role that has an optional parameter that defaults to true. If it's false, it doesn't set latest. If it's true then it simply sets the link. Sort of a "Do you want me to set a 'latest' link to this thing your setting?" That's about it. I've forked this and am working it out in my librarian. If I come up with something cool I'll let you know.

Writing it out, it does seem silly to have a latest that could be an older version, but I suppose it means it's what I want the developers and applications to use, not the latest Oracle version. I'll have to think on it now. I only use the tar.gz deploy and I think I got used to it setting 'latest'. Definitely an enhancement. :)

**Comment by antoineco** [comment]
> I suppose it means it's what I want the developers and applications to use, not the latest Oracle version

Isn't it what `default` is for? This link works as you described: it always points to the version installed by the main class. It allows you to create an alternative for `java` which does not necessarily point to the most recent version.

In the example below, `/use/java/default` points to Java 7, not Java 8;

``` puppet
class { 'oracle_java': version => '7u45' } ->
oracle_java::installation { '8u65': }
```

**Comment by antoineco** [comment]
ping @staylorx.
What do you think about my suggestion to use the "default" symlink?

**Comment by staylorx** [comment]
Thanks for the ping! The group I'm working with likes 'latest', but I'm starting to move more and more to 'default'. I think this can be closed. I was thinking maybe to save a step in the manifest to set 'latest', but that is specific to my installation not the general.

So long as setting 'default' is optional then I've got what I need. It's possible for me to stage SDK/JDKs ahead of switching the default symlink. So I don't want default set all the time.

**Comment by antoineco** [comment]
Got it. In the case of an installation from a tar.gz archive the default symlink is always declared. Would it help if I made it optional using a Boolean parameter?
