### ISSUE TITLE
More then one java package

### ISSUE THREAD

**Issue by peceka** [antoineco/aco-oracle_java#3]
Hi!
There would be nice to have possibility to install more the one package of java on node. :)

Regards,
p.

**Comment by antoineco** [comment]
Took me some time, but there it is! It's arguably not elegant but at least consistent with the main class.

Example of use:

```
class { oracle_java:
  version         => '8u45',
  type            => 'jdk',
  add_alternative => true
}->
oracle_java::installation { '7u65':
  type            => 'jre',
  add_alternative => true
}
```

Feedback would be appreciated before merging.

**Comment by antoineco** [comment]
@peceka did you find the time to try the feature?
