### ISSUE TITLE
Found no way to install both jdk and jre (puppet "redeclaration" error)

### ISSUE THREAD

**Issue by rainer042** [antoineco/aco-oracle_java#30]
Hello,

I would like to install both jre and jdk on a system using oracle_java class (puppet 3.8.5), but I did not find a way to do this. Because classes are unique in puppet I cannot have two oracle_java class declarations, one for jre and the other for jdk installation. 

Is there way to do this using oracle_java? if not then I think it would great to have such an option. If it is possible please tell me how and perhaps add a demo to the documentation.

Thanks a lot
Rainer

**Comment by antoineco** [comment]
Hi Rainer,

You can do that using the `oracle_java::installation` type, just like in the example available in the module documentation. For your reference I'll copy it here:

```puppet
class { 'oracle_java':
  version => '8u112',
  type    => 'jre'
} ->
oracle_java::installation { '8u112':
  type => 'jdk'
}
```

Result:
```
root@c499cef1051b:/# ls -l /usr/java/
total 8
lrwxrwxrwx 1 root root   22 Jan 16 13:05 default -> /usr/java/jre1.8.0_112
drwxr-xr-x 8 root root 4096 Sep 23 04:24 jdk1.8.0_112
drwxr-xr-x 6 root root 4096 Sep 23 04:21 jre1.8.0_112
```
That said, the Oracle JDK *always comes together with the corresponding JRE*, which is installed inside `/usr/java/jdk<version>/jre`.

Feel free to reopen the issue if you have any problem with the proposed solution :)
