### ISSUE TITLE
Inconsistent proxy setting mechanism

### ISSUE THREAD

**Issue by cliffano** [antoineco/aco-oracle_java#39]
For proxy setting in aco-oracle_java, is the intention for user to explicitly set proxy setting as attributes? or for user to set environment variables and then aco-oracle_java will honour http_proxy, https_proxy, and no_proxy?

`download.pp` manifest explicitly set the proxy setting by setting Archive proxy attributes https://github.com/antoineco/aco-oracle_java/blob/master/manifests/download.pp#L24

However, `puppet_x/util.rb` doesn't explicitly set any proxy detail and I assume it relies on Net::HTTP to honour proxy environment variable.
https://github.com/antoineco/aco-oracle_java/blob/master/lib/puppet_x/util.rb#L22

So which one is the intended way of setting proxy in aco-oracle_java?

**Comment by antoineco** [comment]
You're right, I did not implement proxy support in the `oracle_sso` function, thanks for pointing this out!

There is no *preferred* way to configure the proxy, but the custom function should definitely consume `proxy_*` parameters. I'll do it as soon as I'm done fixing the SSO function (see #40).

**Comment by antoineco** [comment]
@cliffano can I close this in favour of the other issue you opened? I think the goal is the same.

**Comment by cliffano** [comment]
Sure thing. Closing this one, resuming discussion on #40 .
