### ISSUE TITLE
version 2.9.1 no longer working

### ISSUE THREAD

**Issue by dalesit** [antoineco/aco-oracle_java#49]
Presumably with the newer versions being released on 16/1/18...

```
Error: Evaluation Error: Error while evaluating a Function Call, Sign-on failed. Check your Oracle.com credentials. at /etc/puppetlabs/code/environments/production/modules/oracle_java/manifests/download.pp:33:17 
```
Running with current master latest works fine. Looks like new release required...

**Comment by antoineco** [comment]
That's right, I wanted to have #43 merged before releasing but the OP didn't respond. Screw that, let's release :)

**Comment by antoineco** [comment]
Released https://forge.puppet.com/aco/oracle_java/2.9.2/changelog
