### ISSUE TITLE
Add JAVA_HOME environment variable

### ISSUE THREAD

**Issue by col-panic** [antoineco/aco-oracle_java#5]
Could you add support as for automated setting of the required environment variables? E.g. JAVA_HOME

thanks

**Comment by antoineco** [comment]
I could, how would you proceed? Adding it to `profile.d` only works for shell sessions, and `/etc/environment` still requires to log-in.

I'm open to whatever sounds right for you.

**Comment by col-panic** [comment]
This should be pretty easy to achieve, at least in Debian, by using the https://wiki.debian.org/DebianAlternatives - i just added it with the following command

update-alternatives --install /usr/bin/java java /usr/java/jre1.8.0_51/bin/java 100

**Comment by col-panic** [comment]
sorry, thats not a solution for JAVA_HOME ... just a start ;) I will look whether I find a good solution!

**Comment by col-panic** [comment]
http://blog.andrewbeacock.com/2007/11/how-to-add-system-wide-environment.html maybe /etc/environment is a start

**Comment by antoineco** [comment]
Released in v2.4.0
