### ISSUE TITLE
Yum / RPM installation issue

### ISSUE THREAD

**Issue by ghost** [antoineco/aco-oracle_java#50]
Hi,

We have the following in a manifest to install Java 161.
  class { 'oracle_java':
    version         => '8u161',
    type            => 'jdk',
    add_alternative => true,
    ssousername     => 'username@domain.com',
    ssopassword     => 'password123',
    before          => Java_ks['server.domain.com:truststore'],
  }

This installed perfectly on our CentOS 7 server:
`[16:01]root@servername:~# puppet agent -t --no-noop
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for servername.domain.com
Info: Applying configuration version '1516635730'
Notice: /Stage[main]/Oracle_java::Download/Archive[/usr/java/jdk-8u161-linux-x64.rpm]/ensure: download archive from http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.rpm?AuthParam=123456789_e2a116cd8a99794ae98ef37518956095 to /usr/java/jdk-8u161-linux-x64.rpm  without cleanup
Info: Class[Oracle_java::Download]: Scheduling refresh of Class[Oracle_java::Install]
Info: Class[Oracle_java::Install]: Scheduling refresh of Class[Oracle_java::Install::Rpm]
Info: Class[Oracle_java::Install::Rpm]: Scheduling refresh of Package[jdk1.8.0_161]
Notice: /Stage[main]/Oracle_java::Install::Rpm/Package[jdk1.8.0_161]/ensure: created
Notice: /Stage[main]/Oracle_java::Install::Rpm/Package[jdk1.8.0_161]: Triggered 'refresh' from 1 event
Notice: /Stage[main]/Oracle_java::Alternative::Rpm/Exec[add java alternative 8u161]/returns: executed successfully
Notice: /Stage[main]/Profiles::Java::Java8/Java_ks[server.domain.com:truststore]/ensure: created
Notice: Applied catalog in 24.93 seconds`

This is the only Java jdk rpm installed.

Unfortunately, subsequent Puppet runs are reporting:

Notice: /Stage[main]/Oracle_java::Install::Rpm/Package[jdk1.8.0_161]/ensure: current_value 'absent', should be 'latest' (noop)

If we run in no-noop it fails with the error that it's already installed!
`Error: Could not update: Execution of '/bin/rpm -i /usr/java/jdk-8u161-linux-x64.rpm' returned 1: package jdk1.8-2000:1.8.0_161-fcs.x86_64 is already installed
Error: /Stage[main]/Oracle_java::Install::Rpm/Package[jdk1.8.0_161]/ensure: change from 'absent' to 'latest' failed: Could not update: Execution of '/bin/rpm -i /usr/java/jdk-8u161-linux-x64.rpm' returned 1: package jdk1.8-2000:1.8.0_161-fcs.x86_64 is already installed`

**Comment by antoineco** [comment]
Found the culprit: https://github.com/antoineco/aco-oracle_java/commit/da907c998fcadc885dfcab7d8fb51dbcf15421dd#diff-60ae41fd0a31977447947f59940ee9a4R200

Thanks for reporting 👍

**Comment by antoineco** [comment]
Fixed in [v2.9.3](https://forge.puppet.com/aco/oracle_java/2.9.3/changelog)
