### ISSUE TITLE
puppet/parser/functions/oracle_sso: undefined method `path' for nil:NilClass 

### ISSUE THREAD

**Issue by DonK5hot** [antoineco/aco-oracle_java#51]
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Could not autoload puppet/parser/functions/oracle_sso: undefined method `path' for nil:NilClass at /etc/puppetlabs/code/environments/general_test/modules/oracle_java/manifests/download.pp:33:17 on node ...

**Comment by antoineco** [comment]
@DonK5hot could you please provide more information about your environment (Puppet agent/server versions) and the parameters you pass to the module?

**Comment by DonK5hot** [comment]
### env
```
puppet 4.10.9
puppetdb-4.4.0-1.el7.noarch
puppetserver-2.8.0-1.el7.noarch
puppetlabs-release-pc1-1.1.0-5.el7.noarch
puppet-agent-1.10.9-1.el7.x86_64
```
### java config:
```
oracle_java::version: '8u161'
oracle_java::installation: 'jre'
oracle_java::install_path: '/usr/java'
oracle_java::add_system_env : true
oracle_java::ssousername: 'email@email.com'
oracle_java::ssopassword: ENC[PKCS7,....
```

**Comment by antoineco** [comment]
Any chance to execute the run again with the debug flag and post the output from Puppet Server?

**Comment by DonK5hot** [comment]
[debug.txt](https://github.com/antoineco/aco-oracle_java/files/1659868/debug.txt)

Attached debug, not sure how useful it is, the only error seem to be one missing arg in /modules/oracle_java/manifests/download.pp
```puppet
  # pass credentials to Oracle SSO for authenticated downloads
  if $oracle_java::oracle_url {
    Archive {
      source => oracle_sso("${oracle_java::download_url_real}/${oracle_java::filename_real}", $oracle_java::ssousername, $oracle_java::ssopassword)
    }
  } else {
    Archive {
      source => "${oracle_java::download_url_real}/${oracle_java::filename_real}"
    }
  }
```

caused by missing fileuri in : /opt/puppetlabs/puppet/cache/lib/puppet/parser/functions/oracle_sso.rb
```ruby
  newfunction(:oracle_sso, :type => :rvalue) do |args|
    fileuri = args[0]
    ssousername = args[1]
    password = args[2]
```

**Comment by antoineco** [comment]
The agent logs won't tell you anything about the error unfortunately because the catalog compilation is happening server side, only the Puppet Server logs can shed lights on the issue.

That said I already see a potential issue:
```
oracle_java::installation: 'jre'
```
This parameter is misused. `installation` is a Puppet type, not a class parameter.
I think you meant:
```
oracle_java::type: 'jre'
```

**Comment by DonK5hot** [comment]
That doesn't really matter, hiera will ignore it and use the default, jre, I just took out that line.
Anyway, I just use oracle_java::add_system_env : true and version 2.8.2, everything works.
Good enough for me.
Thanks!
