### ISSUE TITLE
Automated update?

### ISSUE THREAD

**Issue by col-panic** [antoineco/aco-oracle_java#9]
Will the plugin automatically update my java version? I 

started with your plugin and it installed java version "1.8.0_51" but now 1.8.0_60 is available and it was not updated. Will this happen automatically?

**Comment by antoineco** [comment]
Only if your java version is set to '8' (as opposed to a specific version like '8u51') and you update the module when I release a version including 8u60 (probably today).

If you don't update the module or use a fixed java version, it won't update java.

**Comment by col-panic** [comment]
Okay, I only set include oracle_java - so  I have to define a full set like
class { 'oracle_java':
  version => 8
}
in order to get the update functionality?!

**Comment by col-panic** [comment]
ah, sry for that I see .. i will have to fetch 2.4.1 :)

**Comment by antoineco** [comment]
Freshly pushed to the Forge, grab it while it's hot :)

**Comment by col-panic** [comment]
Unfortunately the update did not work ... it is still serving java version "1.8.0_51" although I grabbed your newest version?!

**Comment by antoineco** [comment]
The update should happen, could you tell me more about your setup?

Here is the protocol I followed on my test environment, based on Fedora 22:

``` bash

#
# install a previous version of the module
#

[root@665e993193bc /]# puppet module install aco-oracle_java -v 2.4.0
/etc/puppet/modules
└─┬ aco-oracle_java (v2.4.0)
  ├─┬ nanliu-archive (v0.3.0)
  │ └── puppetlabs-pe_gem (v0.1.1)
  └── puppetlabs-stdlib (v4.8.0)

#
# declare the oracle_java class
#

[root@665e993193bc /]# puppet apply -e 'include oracle_java' 
...
Notice: /Stage[main]/Oracle_java::Install::Rpm/Package[jre1.8.0_51]/ensure: created
Notice: /Stage[main]/Oracle_java::Install::Rpm/Package[jre1.8.0_51]: Triggered 'refresh' from 1 events
Notice: Applied catalog in 40.75 seconds

#
# check java version
#

[root@665e993193bc /]# java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

#
# upgrade the module to 2.4.1
#

[root@665e993193bc /]# puppet module upgrade aco-oracle_java         
/etc/puppet/modules
└── aco-oracle_java (v2.4.0 -> v2.4.1)

#
# declare the oracle_java class again
#

[root@665e993193bc /]# puppet apply -e 'include oracle_java' 
Notice: /Stage[main]/Oracle_java::Install::Rpm/Package[jre1.8.0_60]/ensure: created
Notice: /Stage[main]/Oracle_java::Install::Rpm/Package[jre1.8.0_60]: Triggered 'refresh' from 1 events
Notice: Applied catalog in 24.83 seconds

#
# check java version
#

[root@665e993193bc /]# java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```

**Comment by col-panic** [comment]
Do I have to re-apply the oracle_java class? I have it as part of my default site.pp and after an update to 2.4.1 the puppet nodes do not update. An execution of 

```
puppet apply -e 'include oracle_java' 
```

on the managed puppet node does result in

```
Error: Could not find class oracle_java for asdfasdfads on node 8asdfasdfasdf
```

so nothing happens here.

**Comment by antoineco** [comment]
You don't have to do anything if it's part of your site.pp.

The error is normal since your node fetches its catalog from the master. `puppet apply` only works if the module is installed locally. 

It seems like a caching issue to me. Did you set an [environment_timeout](https://docs.puppetlabs.com/references/latest/configuration.html#environmenttimeout) by any chance? What happens if you restart your master and do a `puppet agent -t` on the node? Could you post the content of the `/usr/java` directory on the node?

**Comment by col-panic** [comment]
A restartet of the master did not change the situation, this is my /usr/java

```
root@80ee739d7ef3:/var/log# ls -l /usr/java/
total 4
lrwxrwxrwx 1 root root   21 Aug 11 13:59 default -> /usr/java/jre1.8.0_51
drwxr-xr-x 6 root root 4096 Jun  9 04:38 jre1.8.0_51
```

I did not set environment_timeout, it's a plain debian install. puppet run is not available on the node

```
Error: Unknown Puppet subcommand 'run'
```

**Comment by antoineco** [comment]
It was a typo, my bad. I edited my comment.

Can you also show me the output of `puppet module list --tree` on the master?

**Comment by col-panic** [comment]
Here you go

```
/etc/puppet/modules
├─┬ puppetlabs-apt (v2.1.1)
│ └── puppetlabs-stdlib (v4.6.0)
├─┬ nightfly-ssh_keys (v0.0.1)
│ └── puppetlabs-concat (v1.2.4)
├── saz-ssh (v2.8.1)
├── puppetlabs-java (v1.4.1)
├── puppetlabs-ntp (v4.0.0)
└─┬ aco-oracle_java (v2.4.1)
  └─┬ nanliu-archive (v0.3.0)
    └── puppetlabs-pe_gem (v0.1.1)
/usr/share/puppet/modules (no modules installed)
```

**Comment by antoineco** [comment]
All dependencies look good. You didn't set `version => '8u51'` anywhere right? site.pp, hiera, ENC, ... 
If not a caching issue I don't see what it could be.

**Comment by col-panic** [comment]
I think it might be due to my puppet configuration! I will re-check! 
thanks for your help!!!

Antoine Cotten schrieb:

**Comment by col-panic** [comment]
It was a configuration failure, and the update worked now, it does however not set the new version as default

```
root@80ee739d7ef3:/var/log# ls -l /usr/java/
total 8
lrwxrwxrwx 1 root root   21 Aug 31 14:08 default -> /usr/java/jre1.8.0_60
drwxr-xr-x 6 root root 4096 Jun  9 04:38 jre1.8.0_51
drwxr-xr-x 6 root root 4096 Aug  4 21:29 jre1.8.0_60
root@80ee739d7ef3:/var/log# java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
```

**Comment by antoineco** [comment]
What is the output of `which java` and `alternatives --display java`?

You might have to set the `add_alternative` parameter for that. If it's already set, make sure the alternative mode is set to "auto" (`alternatives --auto java`). Maybe it's disabled by default on Debian, I'll check that tonight.

Thanks for the input!

**Comment by col-panic** [comment]
my debian output is as follows

```
root@80ee739d7ef3:~# update-alternatives --display java
java - auto mode
  link currently points to /usr/java/jre1.8.0_51/bin/java
/usr/java/jre1.8.0_51/bin/java - priority 100
Current 'best' version is '/usr/java/jre1.8.0_51/bin/java'.
root@80ee739d7ef3:~# which java
/usr/bin/java
root@80ee739d7ef3:~# dir /usr/java/
default  jre1.8.0_51  jre1.8.0_60
```

it is also the case, that the update resp. the install did not remove the old version

**Comment by antoineco** [comment]
The old versions are not removed to avoid force-uninstalling things that were not created by Puppet. It's a good practice to implement your own cleaners if you want to get rid of artifacts.

Regarding the alternative, you have to set the `add_alternative` class parameter to `true`. Apparently you did it the first time but removed it afterwards, so 8u60 was not added to the list.
